# Generated by Django 4.2.3 on 2023-08-05 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_name_contact_naae'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='naae',
            new_name='name',
        ),
    ]
