# Generated by Django 4.2.3 on 2023-08-05 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_naae_contact_name'),
    ]

    operations = [
    ]
