# Generated by Django 4.2.3 on 2023-08-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230805_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usern', models.TextField(max_length=30)),
                ('passw', models.TextField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.TextField(max_length=30),
        ),
    ]
